shell = '/bin/zsh'
live_config_reload = true


[window]
opacity = 0.7

[scrolling]
history = 50000

[font]
normal = { family = "Inconsolata Nerd Font", style = "Medium" }

[selection]
save_to_clipboard = true
